name = input("What is your name? ") 
print("Hello,", name) 
favorite_nfl_team = input("What is your favorite NFL team? ")
print("Your favorite NFL team is the", favorite_nfl_team)
favorite_card_brand = input("What is your favorite card brand? ")
print("Your favorite card brand is", favorite_card_brand)
city = input("What city do you live in? ")
print("You live in", city)
state = input("What state do you live in? ")
print("You live in", state)
dream_job = input("What is your dream job? ")
print("That's awesome! \nI hope you become a", dream_job, "someday!")
